services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./frontend/.env.development:/app/.env
    working_dir: /app
    command: sh -c "npm install && npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true
