services:
  database:
    image: postgres:14
    container_name: litera-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: litera-pgadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@litera.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - database

  backend:
    build: ./backend
    container_name: litera-backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    env_file: ./backend/.env
    depends_on:
      - database

  frontend:
    build:
    context: ./frontend
    args:
      REACT_APP_GRAPHQL_API_URL: ${REACT_APP_GRAPHQL_API_URL}
    container_name: litera-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  postgres_data:
  pgadmin_data:
