version: "3.8"

services:
  database:
    image: postgres:14
    container_name: litera-db-test
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: litera
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d litera"]
      interval: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: litera-backend-test
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://user:password@database:5432/litera
    command: npm test

  frontend:
    build: ./frontend
    container_name: litera-frontend-test
    depends_on:
      - backend
    command: npm test
