services:
  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_GRAPHQL_API_URL=http://localhost:4000/graphql
