version: "3.8"

services:
  database:
    image: postgres:14
    env_file:
      - .env.ci
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build: ./backend
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env.ci
    command: npm run test
    volumes:
      - ./backend:/app
      - /app/node_modules
